// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: invoices.proto

package billingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Approved      bool                   `protobuf:"varint,5,opt,name=approved,proto3" json:"approved,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,6,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_invoices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Invoice) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Invoice) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Invoice) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *Invoice) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_invoices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_invoices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

type ApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_invoices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{3}
}

func (x *ApproveRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type ApproveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	mi := &file_invoices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{4}
}

func (x *ApproveResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

var File_invoices_proto protoreflect.FileDescriptor

const file_invoices_proto_rawDesc = "" +
	"\n" +
	"\x0einvoices.proto\x12\n" +
	"billing.v1\"\xa6\x01\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bapproved\x18\x05 \x01(\bR\bapproved\x12\x1f\n" +
	"\vapproved_by\x18\x06 \x01(\tR\n" +
	"approvedBy\"$\n" +
	"\vListRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"?\n" +
	"\fListResponse\x12/\n" +
	"\binvoices\x18\x01 \x03(\v2\x13.billing.v1.InvoiceR\binvoices\"/\n" +
	"\x0eApproveRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\"@\n" +
	"\x0fApproveResponse\x12-\n" +
	"\ainvoice\x18\x01 \x01(\v2\x13.billing.v1.InvoiceR\ainvoice2\x89\x01\n" +
	"\bInvoices\x129\n" +
	"\x04List\x12\x17.billing.v1.ListRequest\x1a\x18.billing.v1.ListResponse\x12B\n" +
	"\aApprove\x12\x1a.billing.v1.ApproveRequest\x1a\x1b.billing.v1.ApproveResponseBEZCgithub.com/gsoultan/anubis-sdk/anubiskit/examples/grpc/pb;billingpbb\x06proto3"

var (
	file_invoices_proto_rawDescOnce sync.Once
	file_invoices_proto_rawDescData []byte
)

func file_invoices_proto_rawDescGZIP() []byte {
	file_invoices_proto_rawDescOnce.Do(func() {
		file_invoices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invoices_proto_rawDesc), len(file_invoices_proto_rawDesc)))
	})
	return file_invoices_proto_rawDescData
}

var file_invoices_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_invoices_proto_goTypes = []any{
	(*Invoice)(nil),         // 0: billing.v1.Invoice
	(*ListRequest)(nil),     // 1: billing.v1.ListRequest
	(*ListResponse)(nil),    // 2: billing.v1.ListResponse
	(*ApproveRequest)(nil),  // 3: billing.v1.ApproveRequest
	(*ApproveResponse)(nil), // 4: billing.v1.ApproveResponse
}
var file_invoices_proto_depIdxs = []int32{
	0, // 0: billing.v1.ListResponse.invoices:type_name -> billing.v1.Invoice
	0, // 1: billing.v1.ApproveResponse.invoice:type_name -> billing.v1.Invoice
	1, // 2: billing.v1.Invoices.List:input_type -> billing.v1.ListRequest
	3, // 3: billing.v1.Invoices.Approve:input_type -> billing.v1.ApproveRequest
	2, // 4: billing.v1.Invoices.List:output_type -> billing.v1.ListResponse
	4, // 5: billing.v1.Invoices.Approve:output_type -> billing.v1.ApproveResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_invoices_proto_init() }
func file_invoices_proto_init() {
	if File_invoices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invoices_proto_rawDesc), len(file_invoices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_invoices_proto_goTypes,
		DependencyIndexes: file_invoices_proto_depIdxs,
		MessageInfos:      file_invoices_proto_msgTypes,
	}.Build()
	File_invoices_proto = out.File
	file_invoices_proto_goTypes = nil
	file_invoices_proto_depIdxs = nil
}
